# configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",

  "BSD-2-Clause",                  # av1-grain, ravif
  "BSD-3-Clause",                  # exr, lebe, subtle
  "ISC",                           # inotify, libloading, untrusted, rustls-webpki
  "NCSA",                          # libfuzzer-sys
  "CC0-1.0",                       # notify (public domain)
  "CDLA-Permissive-2.0",           # webpki-roots

  "Apache-2.0 WITH LLVM-exception", # target-lexicon

  "MPL-2.0",                       # option-ext
]


exceptions = [
  { name = "hyprland", allow = ["GPL-3.0-or-later"] },
  { name = "hyprland-macros", allow = ["GPL-3.0-or-later"] },
]

[advisories]
version = 2
ignore = [
  # --- Build-only quick-xml vulnerabilities via xcb ---
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",

  # --- Unmaintained GTK3 ---
  "RUSTSEC-2024-0413",
  "RUSTSEC-2024-0416",
  "RUSTSEC-2024-0412",
  "RUSTSEC-2024-0418",
  "RUSTSEC-2024-0411",
  "RUSTSEC-2024-0414",
  "RUSTSEC-2024-0415",
  "RUSTSEC-2024-0420",
  "RUSTSEC-2024-0419",
  "RUSTSEC-2024-0370",
  "RUSTSEC-2024-0436",
]

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
